= Digital Input/output library for Arduino DIO2 =

This library providest fast digital read and write.

Originaly written by Jan Dolinay, updated by Thierry Paris.

Original sources from Jan available here: https://github.com/jdolinay/Arduino_DIO2 . Article here https://www.codeproject.com/Articles/732646/Fast-digital-I-O-for-Arduino

For more information about this library please visit us at
http://www.locoduino.org/spip.php?article165 in french

== License ==

Copyright (c) Jan Dolinay, All right reserved.
Copyright (c) 2016-2021 Locoduino.org. All right reserved.
Copyright (c) 2016-2021 Thierry Paris. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 3 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
